# Generated by Django 6.0.2 on 2026-03-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=100)),
                ('Department_Description', models.TextField()),
                ('Department_Image', models.ImageField(upload_to='Department_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Qualification', models.CharField(max_length=200)),
                ('Experience', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
            ],
        ),
    ]
