# Generated by Django 6.0.2 on 2026-03-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdb',
            name='Department_Image',
            field=models.ImageField(blank=True, null=True, upload_to='department/'),
        ),
        migrations.AlterField(
            model_name='doctordb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/'),
        ),
        migrations.AlterField(
            model_name='doctordb',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
