# Generated by Django 6.0.2 on 2026-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('Appointment_Date', models.DateField(blank=True, null=True)),
                ('Appointment_Time', models.TimeField(blank=True, null=True)),
                ('Reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
